export default {
  home: "home",
  favorite: "favorite",
  favorites: "favorites",
  add_to_favorites: "add to favorites",
  loading_data: "Retrieving data...",
  cryptocurrency_prices: "Cryptocurrency Prices",
  cryptocurrency_favorites: "Crypto Favorites",
  no_result: "No result found.",
  name: "Name",
  current_price: "Price now",
  market_cap: "Market Cap",
  total_volume: "Total Volume",
  last_7_day: "Last 7 Days",
  search_a_name: "Search a name...",
  no_graphic_found: "No graphic found",
  fetch_data_error: "An error occurred while retrieving data - wait 60 seconds and try again.",
  retry: "Retry",
  day: "Day",
  page_not_found: "Page not found",
  click_to_go_back: "Click here to go back home",
  click_to_router_history: "Or click here to go back to the previous page",
}
