export default {
  home: "accueil",
  favorite: "favori",
  favorites: "favoris",
  add_to_favorites: "Ajouter aux favoris",
  loading_data: "Récupération des données",
  cryptocurrency_prices: "Prix des cryptomonnaies",
  cryptocurrency_favorites: "Crypto Favoris",
  no_result: "Aucun résultat trouvé",
  name: "Nom",
  current_price: "Prix",
  market_cap: "Market Cap",
  total_volume: "Volume Total",
  last_7_day: "Derniers 7 jours",
  search_a_name: "Rechercher un nom...",
  no_graphic_found: "Aucun graphique disponible",
  fetch_data_error: "Une erreur est survenue lors de la récupération des données - attendez 60 secondes et réessayez.",
}
